# Generated by Django 4.2 on 2024-11-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BASE_USER', 'Base user'), ('COUNCELLOR', 'Councellor'), ('EXAMINER', 'Examiner'), ('ACCOUNTANT', 'Accountant'), ('ADMIN', 'Admin'), ('FACULTY', 'Faculty')], default='BASE_USER', max_length=20, null=True),
        ),
    ]
